# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
rust:
  - nightly
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=zokrates

matrix:
  include:
    # Linux
    # - env: TARGET=aarch64-unknown-linux-gnu
    # - env: TARGET=arm-unknown-linux-gnueabi
    # - env: TARGET=i686-unknown-linux-gnu
    # - env: TARGET=x86_64-unknown-linux-gnu

    # # OSX
    # - env: TARGET=i686-apple-darwin
    #   os: osx
    # - env: TARGET=x86_64-apple-darwin
    #   os: osx

    # # *BSD
    # - env: TARGET=x86_64-unknown-freebsd

    - env: TARGET=x86_64-pc-windows-gnu
    - env: TARGET=x86_64-pc-windows-msvc

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: s3
  access_key_id: "AKIAITSVMKXUVHEDEPLQ"
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  secret_access_key:
    secure: "WK3WkT3l1T8KMHtjs4IShyNkf6Q4XdLN25VfNPGJZOK/KNfwy7hrvajlxv3fvXpKa5WuxmdQfZdbFIvZomSN5useZkIGfVdTE4HgMr9t7iOzT4e1HDfenmgkhHmAgZ7K6W5YUrqI4aXQwfTNPTdMMZXDmWl5bQKOVTH3mYTB8JZgUy8Xvb9UHghJc2TDbqMzGCV+m5UxLiLOF4KhEqAKrNRcmv8FyUqzpwqSlv5OjbncRcH3WtnpTtbvHMz+NaoVgXem48QrnMXtr530DVosnJJmjIcVLDU1XIfZmLBNnYxsNQtWlwXkYJrqkGNk9jV//ItBA8d2VRfIx4Dvc7RgKd+GAUyfzfOznPgWF8bA+0Cfog1funXdhMrXLNLPxMb4pnCPcHvZp1z95AsisqiPGXdIHKGl3o/pmjUBBZPiN9MK6m05O3xluYDYbGDlDjqwbrCvV9VVAB/YlAi/1VA3jacyRkqwXFZhZD4MeXKvjqXxtFo+WYvaCvipaOfzyeW1g0PU3xreJtQArVfOXLgdrmHToeJJhjqZGPhkZO7M4rkFbH9Zt+JPgSudVP9Wcs81AeG8kKVPUIVuCOicsMquD4KYNFhhwOeUjaG+xI7G1G/QfIZWP8shC64w6GlO9xPd/eCA7TrIsC8b56Y2XrCqaeBKMoKxZM+rspQL9qYteyY="
  bucket: zokrates
  skip_cleanup: true
  on:
    branch: windows-build

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

# branches:
#   only:
#     # release tags
#     - /^\d+\.\d+\.\d+.*$/
#     - master

notifications:
  email:
    on_success: never
