[package]
name = "zokrates_embed"
version = "0.1.0"
authors = ["schaeff <thibaut@schaeff.fr>"]
edition = "2018"

[features]
default = []
wasm = ["bellman_ce/wasm", "sapling-crypto_ce/wasm"]
multicore = ["bellman_ce/multicore", "sapling-crypto_ce/multicore"]

[dependencies]
bellman_ce = { git = "https://github.com/schaeff/bellman", branch = "fix-zero-sized-chunk", default-features = false}
sapling-crypto_ce = { version = "0.1.1", default-features = false }