[package]
name = "zokrates_field"
version = "0.3.5"
authors = ["Thibaut Schaeffer <thibaut@schaeff.fr>", "Guillaume Ballet <gballet@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.4"
bincode = "0.8.0"
serde_json = "1.0"
bellman_ce = { version = "=0.3.3", default-features = false}
algebra-core = { git = "https://github.com/scipr-lab/zexe.git", default-features = false, optional = true }
sha2 = "0.8.0"
num-traits = { version = "0.2", default-features = false }
num-integer = { version = "0.1", default-features = false }
pairing_ce = "0.20"
ff_ce = { features = ["derive"], version = "0.9" }

[dev-dependencies]
rand = "0.4"

[dependencies.num-bigint]
version = "0.2"
features = ["serde"]
